//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class NoteEdits
    {
        public int Id { get; set; }
        public string Author { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public string Mood { get; set; }
        public System.DateTime DateEdited { get; set; }
        public string CustomerId { get; set; }
        public int NoteId { get; set; }
    
        public virtual Note Note { get; set; }
    }
}
